# Generated by Django 5.0.7 on 2024-08-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'permissions': [('cancel_order', 'Can Cancel Order')]},
        ),
    ]
